logLevel: INFO
force:
    enabled: false
    count: -1
    percent: -1
idle:
    enabled: true
    duration: 60 # Seconds
    activity:
        - PlayerMoveEvent
        - AsyncPlayerChatEvent
        - PlayerInteractEvent
        - PlayerDropItemEvent
        - PlayerToggleSneakEvent
        - PlayerItemHeldEvent
        - PlayerJoinEvent
        - PlayerChangedWorldEvent
        - EnchantItemEvent
        - PrepareItemEnchantEvent
        - InventoryClickEvent
    awayIdle: false
temporaryBed:
    enabled: false
    duration: 600 # Seconds
reward:
    enabled: false
    Golden Apple Satiation:
        class: Food
        saturation: 9.6
        level: 0
        factor: 0.0
    Golden Apple Regeneration:
        class: PotionEffect
        type: REGENERATION
        duration: 4
        amplifier: 1
        factor: 0.0
    Exhaustion Reset:
        class: Health
        health: 0
        exhaustion: -100.0
        factor: 0.0
    Experience Orbs:
        class: ExperienceOrb
        quantity: 3
        experience: 3
        factor: 0.5
sleep: true
bedNoticeLimit: 10 # Seconds (bedEnter and bedLeave only)
messages:
    bedEnter: '§8%1$tH:%1$tM:%1$tS %2$s §dentered bed§8 (need §d+%3$d§8 to sleep)' # 2 = Player Display Name, 3 = Player Count Needed, 4 = Player Count In Bed, 5 = Player Count Possible
    bedLeave: '§8%1$tH:%1$tM:%1$tS %2$s §5left bed§8 (need §d+%3$d§8 to sleep; %4$d in bed)' # 2 = Player Display Name, 3 = Player Count Needed, 4 = Player Count In Bed, 5 = Player Count Possible
    interrupt: '§8%1$tH:%1$tM:%1$tS %2$s §5interrupted sleep§8 (need §d+%3$d§8 to sleep)' # 2 = Player Display Name, 3 = Player Count Needed, 4 = Player Count In Bed, 5 = Player Count Possible
    forceCommand: '§8%1$tH:%1$tM:%1$tS %2$s§8 forced the sun to rise' # 2 = Player Display Name, 3 = Player Count Needed, 4 = Player Count In Bed, 5 = Player Count Possible
    forceConfig: '§8%1$tH:%1$tM:%1$tS Sleep has forced the sun to rise' # 2 = Plugin Name, 3 = Player Count Needed, 4 = Player Count In Bed, 5 = Player Count Possible
    status: '-> %4$d player(s) in bed (need §d+%3$d§8 to sleep)' # 2 = Plugin Name, 3 = Player Count Needed, 4 = Player Count In Bed, 5 = Player Count Possible
    temporaryBedInstruction: '-> §9To revert to previous spawn, destroy this bed soon' # 2 = Duration Until Commit
    temporaryBedReverted: '-> §aReverted spawn to previous bed'
    worldNotFound: '-> World §enot found' # 2 = World
    sleepNotManaged: '-> Sleep state for [%2$s] is §enot managed' # 2 = World
    sleepDisabled: '-> Sleep is §edisabled§r for %2$s' # 2 = World
    requireSleeper: '-> §eNeed at least one§r player in bed to force sleep'
    forceSuccess: '-> §aForcing§r sleep in [%2$s]...' # 2 = World
    noneInBed: '-> No one is currently in bed'
    notSleeping:
        format: '-> %2$d players §5not in bed§r: %3$s' # 2 = Player Count Not Sleeping, 3 = Player Display Names Not In Bed
        +player: '%1$s§r' # 1 = Player Display Name
        +delimiter: ', '
    statusDetail: '-> Sleep needs §d%3$d more§r in bed (%4$d in bed out of %5$d possible = %2$d%%)' # 2 = Percent In Bed, 3 = Player Count Needed, 4 = Player Count In Bed, 5 = Player Count Possible
    commandDisabled: '-> Command §cdisabled' # 2 = Command , 3 = Label
    requiresPlayer: '-> Command cancelled when §cnot in-game player'
    reload: '-> Sleep plugin §2reloaded'
awayBack:
    enabled: false
    activity:
        - AsyncPlayerChatEvent
        - PlayerBedEnterEvent
        - PlayerBedLeaveEvent
    messages:
        awayAlready: '-> You have §ealready been away§r %2$s for %3$s' # 2 = Duration, 3 = Reason
        +awayDefaultReason: 'no reason'
        awayBroadcast: '§8%1$tH:%1$tM:%1$tS %2$s§8 is §3away§8 for §7%3$s' # 2 = Player Display Name, 3 = Away Reason
        backBroadcast: '§8%1$tH:%1$tM:%1$tS %2$s§8 is §6back§8 after §7%3$s§8 for §7%4$s' # 2 = Player Display Name, 3 = Away Reason, 4 = Away Duration
        backNotAway: '-> You are §enot currently away'
version: @VERSION@