name: @NAME@
description: Manages sleep criteria and notifications
softdepend: [PlayerActivity]
version: @VERSION@
author: @AUTHOR@
main: @MAIN@
commands:
    'sleep:status':
        aliases: [sleep, sleep.status]
        description: Sleep requirements and who is preventing sleep
        permission: sleep.status
        usage: /<command>[ <World>]
    'sleep:force':
        aliases: [sleep.force]
        description: Force sleep for one night
        permission: sleep.force
        usage: /<command>[ <World>]
    'sleep:away':
        aliases: [away, afk]
        description: Configure your status as not active
        permission: sleep.away
        usage: /<command>[ <Reason>]
    'sleep:back':
        aliases: [back]
        description: Configure your status as no longer away
        permission: sleep.back
        usage: /<command>
    'sleep:reload':
        description: Reload Sleep plugin
        permission: sleep.reload
        usage: /<command>
permissions:
    sleep.admin:
        description: 'Can use administrative features of Sleep plugin'    
        default: op
        children:
            sleep.user: true
            sleep.force: true
            sleep.reload: true
    sleep.user:
        description: 'Can use basic features of Sleep plugin'
        default: true
        children:
            sleep.status: true
            sleep.awayback: true
    sleep.ignore:
        description: 'Will always be ignored for sleep'
        default: false
    sleep.enter.force:
        description: 'Will automatically force sleep when entering bed'
        default: false
    sleep.away:
        description: 'Can use sleep:away command'
        default: false
    sleep.back:
        description: 'Can use sleep:back command'
        default: false
    sleep.awayback:
        description: 'Can use sleep:away and sleep:back commands'
        default: false
        children:
            sleep.away: true
            sleep.back: true
    sleep.status:
        description: 'Can use sleep:status command'
        default: false
    sleep.force:
        description: 'Can use sleep:force command'
        default: false
    sleep.reload:
        description: 'Can use sleep:reload command'
        default: false