name: Sleep
description: Manages sleep based on activity or minimum criteria.
version: %VERSION%
depend: [MessageManager]
author: EdGruberman (ed@rjump.com)
main: edgruberman.bukkit.sleep.Main
commands:
    sleep:
        description: Manages sleep functionality.
        permission: sleep.sleep
        usage: |
            /<command>[ status[ <World>]] - Display how many players still needed for sleep in <World>.
            /<command> who[ <World] - Display who is in bed in <World>.
            /<command> detail[ <World>] - Display sleep requirements in <World>.
            /<command> reload - Reload configuration files.
permissions:
    sleep.sleep.info:
        description: Can use all the basic information actions of the sleep command.
        default: true
        children:
            sleep.sleep.status: true
            sleep.sleep.who: true
            sleep.sleep.detail: true
    sleep.sleep:
        description: Can use sleep command.
        default: op
    sleep.sleep.status:
        description: Can use status action of sleep command.
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.who:
        description: Can use who action of sleep command.
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.detail:
        description: Can use detail action of sleep command.
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.reload:
        description: Can use reload action of sleep command.
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.ignore:
        description: Player will always be ignored for sleep.
        default: false
        children:
            sleep.sleep: true