name: Sleep
version: @VERSION@
description: Manages sleep criteria and notifications
softdepend: [PlayerActivity]
author: EdGruberman (ed@rjump.com)
website: http://dev.bukkit.org/server-mods/sleep/
main: edgruberman.bukkit.sleep.Main
commands:
  'status':
    description: Sleep requirements and who is preventing sleep
    permission: sleep.status
    usage: '§f-> §7Usage: §b/<command> §3[§oworld§3]'
  'force':
    description: Force sleep for one night
    permission: sleep.force
    usage: '§f-> §7Usage: §b/<command> §3[§oworld§3]'
  'sleep.reload':
    description: Reload Sleep plugin
    permission: sleep.reload
    usage: '§f-> §7Usage: §b/<command>'
permissions:
  sleep.admin:
    description: Can use all features of Sleep plugin    
    default: op
    children:
      sleep.user: true
      sleep.force: true
      sleep.reload: true
  sleep.user:
    description: Can use basic features of Sleep plugin
    default: true
    children:
      sleep.consider: true
      sleep.status: true
      sleep.idle: true
      sleep.away: true
      sleep.daybed: true
  sleep.consider:
    description: Allows preventing sleep if not in bed
    default: false
  sleep.idle:
    description: Allows being ignored while idle if Idle supplement is enabled
    default: false
  sleep.away:
    description: Allows being ignored while away if Away supplement is enabled
    default: false
  sleep.daybed:
    description: Allows setting bed spawn during the day if Daybed supplement is enabled
    default: false
  sleep.enter.force:
    description: Will automatically force sleep when entering bed
    default: false
  sleep.status:
    description: Can use status command
    default: false
  sleep.force:
    description: Can use force command
    default: false
  sleep.reload:
    description: Can use reload command
    default: false
  sleep.ignore:
    description: DEPRECATED - Use sleep.consider instead
    default: false
    children:
      sleep.consider: false