name: @NAME@
description: Manages sleep criteria and notifications for multi-player environments
softdepend: [MessageManager, PlayerActivity]
version: @VERSION@
author: @AUTHOR@
main: edgruberman.bukkit.sleep.Main
commands:
    sleep:
        description: Manages sleep functionality
        permission: sleep.sleep
        usage: |
            /<command>[ status[ <World>]] - Display how many players still needed for sleep in <World>
            /<command> detail[ <World>] - Display sleep requirements in <World>
            /<command> who[ <World] - Display who is in bed in <World>
            /<command> force[ <World>] - Force sleep in <World>
            /<command> reload - Reload configuration files
permissions:
    sleep.sleep.info:
        description: Can use all the basic information actions of the sleep command
        default: true
        children:
            sleep.sleep.status: true
            sleep.sleep.who: true
            sleep.sleep.detail: true
    sleep.sleep:
        description: Can use sleep command
        default: op
    sleep.sleep.status:
        description: Can use status action of sleep command
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.who:
        description: Can use who action of sleep command
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.detail:
        description: Can use detail action of sleep command
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.reload:
        description: Can use reload action of sleep command
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.force:
        description: Can use force action of sleep command
        default: op
        children:
            sleep.sleep: true
    sleep.ignore:
        description: Will always be ignored for sleep
        default: false
    sleep.notify:
        description: Messages will be generated for all sleep related activities and commands
        default: true
        children:
            sleep.notify.ENTER_BED: true
            sleep.notify.LEAVE_BED: true
            sleep.notify.FORCE_COMMAND: true
            sleep.notify.INTERRUPT: true
    sleep.notify.ENTER_BED:
        description: Will notify local world in which player has entered bed
        default: false
    sleep.notify.LEAVE_BED:
        description: Will notify local world in which player has left bed manually
        default: false
    sleep.notify.FORCE_COMMAND:
        description: Will notify target world that has been forced to sleep from a player action or command
        default: false
    sleep.notify.INTERRUPT:
        description: Will notify target world that was just about to sleep that a new player joined
        default: false
    sleep.force:
        description: Will automatically force sleep when entering bed
        default: false