name: Sleep
description: Manages sleep based on activity or minimum criteria.
version: %VERSION%
depend: [MessageManager]
author: EdGruberman (ed@rjump.com)
main: edgruberman.bukkit.sleep.Main
commands:
    sleep:
        description: Manages sleep functionality.
        usage: |
            /<command>[ status[ <World>]] - Display how many players still needed for sleep in <World>.
            /<command> who[ <World] - Display who is in bed in <World>.
            /<command> details[ <World>] - Display sleep requirements in <World>.
            /<command> reload - Reload configuration files.
permissions:
    edgruberman.bukkit.sleep.command.sleep.info:
        description: Can use all the basic information actions of the sleep command.
        children:
            edgruberman.bukkit.sleep.command.sleep.action.status: true
            edgruberman.bukkit.sleep.command.sleep.action.who: true
            edgruberman.bukkit.sleep.command.sleep.action.detail: true
    edgruberman.bukkit.sleep.command.sleep.status:
        description: Can use status action of sleep command.
        default: op
    edgruberman.bukkit.sleep.command.sleep.who:
        description: Can use who action of sleep command.
        default: op
    edgruberman.bukkit.sleep.command.sleep.detail:
        description: Can use detail action of sleep command.
        default: op
    edgruberman.bukkit.sleep.command.sleep.reload:
        description: Can use reload action of sleep command.
        default: op
    edgruberman.bukkit.sleep.ignore:
        description: Player will always be ignored for sleep