name: Sleep
description: Manages sleep criteria and notifications for multi-player environments.
version: %VERSION%
depend: [MessageManager]
author: EdGruberman (ed@rjump.com)
main: edgruberman.bukkit.sleep.Main
commands:
    sleep:
        description: Manages sleep functionality.
        permission: sleep.sleep
        usage: |
            /<command>[ status[ <World>]] - Display how many players still needed for sleep in <World>.
            /<command> detail[ <World>] - Display sleep requirements in <World>.
            /<command> who[ <World] - Display who is in bed in <World>.
            /<command> force[ safe][ <World>] - Force sleep in <World>. (No nightmares if safe.)
            /<command> reload - Reload configuration files.
permissions:
    sleep.sleep.info:
        description: Can use all the basic information actions of the sleep command.
        default: true
        children:
            sleep.sleep.status: true
            sleep.sleep.who: true
            sleep.sleep.detail: true
    sleep.sleep:
        description: Can use sleep command.
        default: op
    sleep.sleep.status:
        description: Can use status action of sleep command.
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.who:
        description: Can use who action of sleep command.
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.detail:
        description: Can use detail action of sleep command.
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.reload:
        description: Can use reload action of sleep command.
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.force:
        description: Can use force action of sleep command.
        default: op
        children:
            sleep.sleep: true
    sleep.sleep.force.safe:
        description: Can use safe option with force action of sleep command.
        default: op
        children:
            sleep.sleep.force: true
    sleep.ignore:
        description: Will always be ignored for sleep.
        default: false
    sleep.notify:
        description: Messages will be broadcasted for sleep related activities.
        default: true
        children:
            sleep.notify.ENTER_BED: true
            sleep.notify.LEAVE_BED: true
            sleep.notify.NIGHTMARE: true
            sleep.notify.FORCE_SLEEP: true
    sleep.notify.ENTER_BED:
        description: Will notify local world in which player has entered bed.
        default: false
    sleep.notify.LEAVE_BED:
        description: Will notify local world in which player has left bed manually.
        default: false
    sleep.notify.NIGHTMARE:
        description: Will notify local world in which player has left bed because of a mob spawn.
        default: false
    sleep.notify.FORCE_SLEEP:
        description: Will notify target world that has been forced to sleep.
        default: false
    sleep.force:
        description: Will automatically force sleep when entering bed.
        default: false