name: @NAME@
description: Manages sleep criteria and notifications
softdepend: [PlayerActivity]
version: @VERSION@
author: @AUTHOR@
main: @MAIN@
commands:
    'sleep:sleep':
        aliases: [sleep]
        description: Sleep requirements and who is preventing sleep
        permission: sleep.sleep
        usage: /<command>[ <World>]
    'sleep:force':
        aliases: [sleep.force]
        description: Force sleep for one night
        permission: sleep.sleep.force
        usage: /<command>[ <World>]
    'sleep:away':
        aliases: [away, afk]
        description: Configure your status as not active
        permission: sleep.away
        usage: /<command>[ <Reason>]
    'sleep:back':
        aliases: [back]
        description: Configure your status as no longer away
        permission: sleep.back
        usage: /<command>
    'sleep:reload':
        description: Reload Sleep plugin
        permission: sleep.reload
        usage: /<command>
permissions:
    sleep.sleep:
        description: Can use sleep command
        default: true
    sleep.sleep.force:
        description: Can use sleep.force command
        default: op
    sleep.ignore:
        description: Will always be ignored for sleep
        default: false
    sleep.autoforce:
        description: Will automatically force sleep when entering bed
        default: false
    sleep.away:
        description: Can use away command
        default: true
    sleep.back:
        description: Can use back command
        default: true
    sleep.away:
        description: Can use away command
        default: false
    sleep.back:
        description: Can use back command
        default: false
    sleep.who:
        description: Can use who command
        default: false
    sleep.awayback:
        description: Can use away and back commands
        default: true
        children:
            sleep.away: true
            sleep.back: true
    sleep.reload:
        description: Can use reload command
        default: op