name: @NAME@
description: Manages sleep criteria and notifications
softdepend: [MessageManager, PlayerActivity]
version: @VERSION@
author: @AUTHOR@
main: @MAIN@
commands:
    'sleep:sleep':
        aliases: sleep
        description: Sleep requirements and who is preventing sleep
        permission: sleep.sleep
        usage: /<command>[ <World>]
    'sleep:sleep.force':
        aliases: [sleep.force]
        description: Force sleep for one night
        permission: sleep.sleep.force
        usage: /<command>[ <World>]
permissions:
    sleep.sleep:
        description: Can use sleep command
        default: true
    sleep.sleep.force:
        description: Can use sleep.force command
        default: op
    sleep.ignore:
        description: Will always be ignored for sleep
        default: false
    sleep.autoforce:
        description: Will automatically force sleep when entering bed
        default: false