sleep: true
idle: 60
force:
    count: -1
    percent: -1
notifications:
    ENTER_BED:
        format: '%1$s&_ entered bed (need +%2$d to sleep)' # 1 = Player Display Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        maxFrequency: 10
        timestamp: false
    LEAVE_BED:
        format: '%1$s&_ left bed (need +%2$d to sleep)' # 1 = Player Display Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        maxFrequency: 10
        timestamp: false
    INTERRUPT:
        format: '%1$s&_ interrupted sleep (need +%2$d to sleep)' # 1 = Player Display Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        maxFrequency: -1
        timestamp: false
    STATUS:
        format: '%3$d&_ player(s) in bed (need +%2$d to sleep)' # 1 = Plugin Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        timestamp: false
    FORCE:
        format: 'Forced sleep' # 1 = Plugin Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        timestamp: false
    FORCE_COMMAND:
        format: '%1$s&_ forced sleep' # 1 = Player Display Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        maxFrequency: -1
        timestamp: false
activity:
    - PlayerMoveEvent
    - PlayerChatEvent
    - PlayerInteractEvent
    - PlayerDropItemEvent
    - PlayerToggleSneakEvent
    - PlayerItemHeldEvent
    - PlayerJoinEvent
    - PlayerChangedWorldEvent
logLevel: INFO
version: @VERSION@