inactivityLimit: 300
safeRadius: 3
force:
    count: null
    percent: null
message:
    enterBed: null
    maxFrequency: 10
    timestamp: false
activity:
    - PLAYER_MOVE
    - PLAYER_CHAT
    - PLAYER_INTERACT
    - PLAYER_DROP_ITEM
    - PLAYER_TOGGLE_SNEAK
    - PLAYER_ITEM_HELD
    - PLAYER_JOIN