sleep: true
idle: 60
force:
    count: -1
    percent: -1
notifications:
    FORCE:
        format: 'Forcing sleep...'
        maxFrequency: -1
        timestamp: false
    FORCE_COMMAND:
        format: '%1$s is forcing sleep...' # 1 = Player Display Name
        maxFrequency: -1
        timestamp: false
    ENTER_BED:
        format: '' # 1 = Player Display Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        maxFrequency: 10
        timestamp: false
    LEAVE_BED:
        format: '' # 1 = Player Display Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        maxFrequency: 10
        timestamp: false
activity:
    - PlayerMoveEvent
    - PlayerChatEvent
    - PlayerInteractEvent
    - PlayerDropItemEvent
    - PlayerToggleSneakEvent
    - PlayerItemHeldEvent
    - PlayerJoinEvent