inactivityLimit: 300
force:
    count: -1
    percent: -1
notifications:
    ENTER_BED:
        format: ''
        maxFrequency: 10
        timestamp: false
    LEAVE_BED:
        format: ''
        maxFrequency: 10
        timestamp: false
    NIGHTMARE:
        format: ''
        maxFrequency: 10
        timestamp: false
    FORCE_SLEEP:
        format: '%1$s has forced sleep.'
        maxFrequency: -1
        timestamp: false
    FORCE_SAFE:
        format: '%1$s has forced safe sleep.'
        maxFrequency: -1
        timestamp: false
activity:
    - PLAYER_MOVE
    - PLAYER_CHAT
    - PLAYER_INTERACT
    - PLAYER_DROP_ITEM
    - PLAYER_TOGGLE_SNEAK
    - PLAYER_ITEM_HELD
    - PLAYER_JOIN