notifications:
    ENTER_BED:
        format: '%1$s&* entered bed (need +%2$d to sleep)' # 1 = Player Display Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        maxFrequency: 10
        timestamp: false
    LEAVE_BED:
        format: '%1$s&* left bed (need +%2$d to sleep)' # 1 = Player Display Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        maxFrequency: 10
        timestamp: false
    INTERRUPT:
        format: '%1$s&* interrupted sleep (need +%2$d to sleep)' # 1 = Player Display Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        maxFrequency: -1
        timestamp: false
    STATUS:
        format: '%3$d&* player(s) in bed (need +%2$d to sleep)' # 1 = Plugin Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        timestamp: false
    FORCE:
        format: 'Sleep has forced the sun to rise' # 1 = Plugin Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        timestamp: false
    FORCE_COMMAND:
        format: '%1$s&* forced the sun to rise' # 1 = Player Display Name, 2 = Player Count Needed, 3 = Player Count In Bed, 4 = Player Count Possible
        maxFrequency: -1
        timestamp: false
idle: 60
activity:
    - PlayerMoveEvent
    - PlayerChatEvent
    - PlayerInteractEvent
    - PlayerDropItemEvent
    - PlayerToggleSneakEvent
    - PlayerItemHeldEvent
    - PlayerJoinEvent
    - PlayerChangedWorldEvent
    - EnchantItemEvent
    - PrepareItemEnchantEvent
    - InventoryClickEvent
force:
    count: -1
    percent: -1
sleep: true
awayIdle: false
logLevel: INFO
version: @VERSION@