sleep: true
inactivityLimit: 60
force:
    count: -1
    percent: -1
notifications:
    ENTER_BED:
        format: ''
        maxFrequency: 10
        timestamp: false
    LEAVE_BED:
        format: ''
        maxFrequency: 10
        timestamp: false
    FORCE:
        format: '%1$s is forcing sleep...'
        maxFrequency: -1
        timestamp: false
    FORCE_CONFIGURATION:
        format: 'Server is forcing sleep...'
        maxFrequency: -1
        timestamp: false
activity:
    - PlayerMoveEvent
    - PlayerChatEvent
    - PlayerInteractEvent
    - PlayerDropItemEvent
    - PlayerToggleSneakEvent
    - PlayerItemHeldEvent
    - PlayerJoinEvent