name: SimpleAwaySleep
description: Allows sleeping to occur if players are not currently active in game.
version: %VERSION%
author: EdGruberman (ed@rjump.com)
main: edgruberman.bukkit.simpleawaysleep.Main
